### ISSUE TITLE
MainActivity.kt lifecycle loop on CommunityFragment.kt permissions request

### ISSUE THREAD

**Issue by phillipsk** [BrightMindEnrichment/StreetCare#60]
Recreation steps:
fresh install of the app
allow notification
navigate to community screen
allow approximate location
confirm allow approximate location
Try to navigate to another screen or tap any interaction

Actual result: app freezes
Expected result: user is able to continue interaction after selecting approximate location

Debugging notes: set a breakpoint in onPause() and onResume() of MainActivity.kt and research permission requests from CommunityFragment.kt

See attached video:

https://github.com/BrightMindEnrichment/StreetCare/assets/7585083/ae2e0377-93af-4e19-af87-5bb675ecdf61

**Comment by SwathiSelvakumaran** [comment]
Issue fixed as part of PR https://github.com/BrightMindEnrichment/StreetCare/pull/63
