### ISSUE TITLE
Badges earned view is misaligned

### ISSUE THREAD

**Issue by phillipsk** [BrightMindEnrichment/StreetCare#62]
As a logged in user when tapping on Badges earned link from the profile fragment view a user should be able to view badges within the screen view. 

![badges_earned](https://github.com/BrightMindEnrichment/StreetCare/assets/7585083/21e68472-e30b-4707-95d6-ebf90e2e2870)

**Comment by yuvavt** [comment]
Fixed the alignment of badges in profile page. Please find the PR raised below for the code changes and screenshot.
https://github.com/BrightMindEnrichment/StreetCare/pull/64
